#!/bin/bash
temp_dir=`mktemp -d`

SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

chmod a-rw $temp_dir
chmod u+rwx $temp_dir
cp -R $DIR/proxy.overlay/* $temp_dir
chmod -R u+rw $temp_dir

UA="Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko"


chromium-browser --user-data-dir="$temp_dir" --no-default-browser-check --bwsi --no-first-run --disable-sync --ignore-certificate-errors --proxy-server=http://127.0.0.1:8080 --disable-background-networking --disable-component-extensions-with-background-pages --dns-prefetch-disable --user-agent="$UA" $@

rm -rf $temp_dir
