#!/bin/bash
temp_dir=`mktemp -d`

SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

chmod a-rw $temp_dir
chmod u+rwx $temp_dir
cp -R $DIR/gchrome.browser.base/* $temp_dir
chmod -R u+rw $temp_dir

UA="Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko"

#chromium-browser --user-data-dir="$temp_dir" --no-default-browser-check --bwsi --no-first-run --disable-sync --user-agent="$UA" $@
google-chrome --user-data-dir="$temp_dir" --no-default-browser-check --bwsi --no-first-run --disable-sync --password-store=basic $@

rm -rf $temp_dir
